"""add canceled_at

Revision ID: 6d7230d4621f
Revises: 5a7e5adc7167
Create Date: 2026-01-21 11:23:22.532850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7230d4621f'
down_revision: Union[str, Sequence[str], None] = '5a7e5adc7167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'canceled_at')
    # ### end Alembic commands ###
